# -*- coding: utf-8 -*-
#
# Copyright (c) 2020, CloudBlue
# All rights reserved.
#

def generate(client, parameters, progress_callback):
    raise RuntimeError("Report has failed due unknown reason")
